# node-modules is required for Hardhat commands to work. Otherwise,
# Hardhat complains that a "non-local" installation is being used.
nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.1.0.cjs
